[package]
name = "metrics-recorder"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.19"
hyper = "0.14.16"
prometheus = "0.13.0"
prometheus-parse = { git = "https://github.com/ccakes/prometheus-parse-rs", rev = "a4574e9" }
